# Generated by Django 3.0.5 on 2020-04-18 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_url', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[(game.models.GameStatus['NEW'], 'New'), (game.models.GameStatus['ACTIVE'], 'Active'), (game.models.GameStatus['COMPLETED'], 'Finished'), (game.models.GameStatus['ABANDONED'], 'Abandoned'), (game.models.GameStatus['PAUSED'], 'Paused'), (game.models.GameStatus['CANCELLED'], 'Exited')], default=game.models.GameStatus['NEW'], max_length=15)),
                ('random_word', models.CharField(max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(default=None)),
                ('result', models.CharField(choices=[(game.models.GameResult['GAME_MASTER_WINS'], 'Word not found'), (game.models.GameResult['SPY_LOSES'], 'Spy discovered'), (game.models.GameResult['SPY_WINS'], 'Spy wins')], max_length=15, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(game.models.PlayerRole['GAME_MASTER'], 'Game Master'), (game.models.PlayerRole['SPY'], 'Spy'), (game.models.PlayerRole['NORMAL'], 'Player')], max_length=15, null=True)),
                ('alias', models.CharField(max_length=15)),
                ('points_earned', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.GameSession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
