# Generated by Django 3.0.5 on 2020-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='completed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
