# Generated by Django 3.0.5 on 2020-04-22 11:06

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200421_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='result',
            field=models.CharField(choices=[('GAME_MASTER_WINS', 'Word not found'), ('SPY_LOSES', 'Spy discovered'), ('SPY_WINS', 'Spy wins')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('COMPLETED', 'Finished'), ('ABANDONED', 'Abandoned'), ('PAUSED', 'Paused'), ('CANCELLED', 'Exited')], default=game.models.GameStatus['NEW'], max_length=25),
        ),
    ]
